// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFKgMInGVk1PMPxMedU_VFKo4nKsJgCJ0',
    appId: '1:37275460253:web:823217dbf11294393c2a74',
    messagingSenderId: '37275460253',
    projectId: 'gebeyia',
    authDomain: 'gebeyia.firebaseapp.com',
    storageBucket: 'gebeyia.appspot.com',
    measurementId: 'G-MBC4DT1YPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvff-UFu9iz1AZbS-Qvb1KuzSEM6rrSM',
    appId: '1:37275460253:android:273097efacb4ae083c2a74',
    messagingSenderId: '37275460253',
    projectId: 'gebeyia',
    storageBucket: 'gebeyia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfFNIh7V3nRbEl5wIDCVhujvJRd9K1mk',
    appId: '1:37275460253:ios:6c8c3e4ba4534d713c2a74',
    messagingSenderId: '37275460253',
    projectId: 'gebeyia',
    storageBucket: 'gebeyia.appspot.com',
    iosBundleId: 'com.example.gebeya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEfFNIh7V3nRbEl5wIDCVhujvJRd9K1mk',
    appId: '1:37275460253:ios:01d590ccb14d8c053c2a74',
    messagingSenderId: '37275460253',
    projectId: 'gebeyia',
    storageBucket: 'gebeyia.appspot.com',
    iosBundleId: 'com.example.gebeya.RunnerTests',
  );
}
